### ISSUE TITLE
Tapable.plugin is deprecated

### ISSUE THREAD

**Issue by goatandsheep** [nuxt/create-nuxt-app#185]
Fresh install gave me this build error:

(node:17605) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

Setup:

* axios
* element-ui
* universal
* eslint

**Comment by manniL** [comment]
That's no error. It's a **warning**. Probably from https://github.com/nuxt-community/pwa-module/issues/120 or another module. Not problematic at all

**Comment by goatandsheep** [comment]
It shows up as an error for me
![Error](https://i.imgur.com/IOOFvOz.png)

**Comment by trylovetom** [comment]
Same Here
Any Update?

**Comment by keng0o** [comment]
same

**Comment by manniL** [comment]
Folks, once again.

1. This is no problematic error but just a `DeprecationWarning`. You can notice that by actually reading the error message.
2. `DeprecationWarning` means that something will not work in the future but still works.
3. This is caused by the [`@nuxtjs/pwa` modules](https://github.com/nuxt-community/pwa-module/issues/120) and will be fixed the next major version. We can't just release a minor because it's a breaking change.
4. There is a beta for `@nuxtjs/pwa` that removes the error. Please try it out :pray:
