### ISSUE TITLE
Custom server frame option missing

### ISSUE THREAD

**Issue by kairosbusinessconsultancy** [nuxt/create-nuxt-app#598]
When a run npx create-nuxt-app, it skipped the custom server framework option to UI framework. It was not mention on nuxt release note as well.
![nuxt-custom-framework](https://user-images.githubusercontent.com/57244880/91961878-60711380-ed3e-11ea-9f08-674f1365f486.png)

**Comment by azrikahar** [comment]
It was mentioned in [the release note for v3.0.0](https://github.com/nuxt/create-nuxt-app/releases/tag/v3.0.0), particularly PR #501. 

From my understanding, they just wanted to move it to separate server templates instead of including it out of the box in this create-nuxt-app. You can read about the [serverMiddleware](https://nuxtjs.org/api/configuration-servermiddleware) which is the recommended approach going forward if I'm not mistaken.

You can read more about the reasoning and links to the server templates like Express, Koa, Adonis etc [over at this comment](https://github.com/nuxt/create-nuxt-app/issues/563#issuecomment-656611288) in #563. Feel free to forward your questions over there since it should be the open issue for this type of question.

**Comment by scott8013** [comment]
I need select koa2 options!
