### ISSUE TITLE
Update Nuxt version

### ISSUE THREAD

**Issue by AdrianoCahete** [nuxt/create-nuxt-app#693]
Fresh installed Nuxt App comes with `2.14.6`. The latest today is `2.14.12`. ([Release Notes](https://nuxtjs.org/docs/release-notes))

Same happens with all other dependencies:
```
dependency            installed →    latest
---------------
@nuxtjs/pwa             ^3.0.2  →    ^3.3.4
core-js                 ^3.6.5  →    ^3.8.3
nuxt                   ^2.14.6  →  ^2.14.12
@nuxtjs/eslint-config   ^3.1.0  →    ^5.0.0
@nuxtjs/eslint-module   ^2.0.0  →    ^3.0.2
eslint                 ^7.10.0  →   ^7.18.0
eslint-plugin-nuxt      ^1.0.0  →    ^2.0.0
```

[ncu](https://www.npmjs.com/package/npm-check-updates) helps with the updates, but of course comes from default will be a lot easier.

**Comment by clarkdo** [comment]
Yes, `^2.x.x` means latests version < 3.0, so it will install latest 2.x version, I think you can run `yarn upgrage nuxt` or remove lock file and re-install.

I think you may not use latest crate-nuxt-app, because the major verison of dependencies you pasted are all latest.

```js
    "@nuxtjs/eslint-config": "^5.0.0",
    "@nuxtjs/eslint-module": "^3.0.2",
    "eslint": "^7.18.0",
    "eslint-config-prettier": "^7.1.0",
    "eslint-plugin-nuxt": "^2.0.0",
```

https://unpkg.com/cna-template@3.5.0/template/nuxt/package.json

**Comment by AdrianoCahete** [comment]
> I think you may not use latest crate-nuxt-app, because the major verison of dependencies you pasted are all latest.

I was using npx in that time, but created a new project yesterday and everything was the latest version, so you did update something that fixed this problem. Thanks either way! Hahaha
